// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPQXgOa4JniOfVTk5OZmyjJlPObU1R5y8',
    appId: '1:918394593301:web:83e077de8e1fbfc41e2e1c',
    messagingSenderId: '918394593301',
    projectId: 'cadillacapp-42c1d',
    authDomain: 'cadillacapp-42c1d.firebaseapp.com',
    storageBucket: 'cadillacapp-42c1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjGyk8ZMeemyk_8WzxcHRTQntaj4002Wk',
    appId: '1:918394593301:android:9257797aefb558ba1e2e1c',
    messagingSenderId: '918394593301',
    projectId: 'cadillacapp-42c1d',
    storageBucket: 'cadillacapp-42c1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGljYNuu-kiyP9KB5746SQqNldqu9KHRM',
    appId: '1:918394593301:ios:5473de6f74b2bc8b1e2e1c',
    messagingSenderId: '918394593301',
    projectId: 'cadillacapp-42c1d',
    storageBucket: 'cadillacapp-42c1d.appspot.com',
    iosClientId: '918394593301-agp2p34vkb9dmqglb77n9f26ci0jet7c.apps.googleusercontent.com',
    iosBundleId: 'com.cadillac.cadillac',
  );
}
